var Particular=new Array()
	Particular[0] = new slctr('Categoria:')
	Particular[1] = new slctr("Informes Financiera",'Informes Financiera')
	Particular[2] = new slctr("Otro",'Otro')		

var Gobierno=new Array()
	Gobierno[0] = new slctr('Categoria:')
	Gobierno[1] = new slctr("Nombramientos",'Nombramientos')
	Gobierno[2] = new slctr("Informe Varios",'Informe Varios')		
	Gobierno[3] = new slctr("Informe Otros",'Informe Otros')
	Gobierno[4] = new slctr("Reglamentos",'Reglamentos')
	Gobierno[5] = new slctr("Convocatorias",'Convocatorias')
	Gobierno[6] = new slctr("Expropiaciones",'Expropiaciones')
	Gobierno[7] = new slctr("Leyes",'Leyes')
	Gobierno[8] = new slctr("Acuerdos",'Acuerdos')
	Gobierno[9] = new slctr("Otros",'Otros')
	
			

var Legislativo=new Array()
	Legislativo[0] = new slctr('Categoria:')
	Legislativo[1] = new slctr("Leyes",'Leyes')
	Legislativo[2] = new slctr("Reformas",'Reformas')		
	Legislativo[3] = new slctr("Decretos",'Decretos')		
	Legislativo[4] = new slctr("Código",'Código')
	Legislativo[5] = new slctr("Reglamentos",'Reglamentos')
	Legislativo[6] = new slctr("Convocatorias",'Convocatorias')
	Legislativo[7] = new slctr("Nombramientos",'Nombramientos')
	Legislativo[8] = new slctr("Expropiaciones",'Expropiaciones')
	Legislativo[9] = new slctr("Leyes",'Leyes')	
	Legislativo[10] = new slctr("Otros",'Otros')	
		

var Judicial=new Array()
	Judicial[0] = new slctr('Categoria:')
	Judicial[1] = new slctr("Resoluciones",'Resoluciones')
	Judicial[2] = new slctr("Notificaciones",'Notificaciones')		
	Judicial[3] = new slctr("Avisos",'Avisos')		
	Judicial[4] = new slctr("Sentencias",'Sentencias')	
	Judicial[5] = new slctr("Reglamentos",'Reglamentos')
	Judicial[6] = new slctr("Convocatorias",'Convocatorias')
	Judicial[7] = new slctr("Nombramientos",'Nombramientos')
	Judicial[8] = new slctr("Expropiaciones",'Expropiaciones')
	Judicial[9] = new slctr("Leyes",'Leyes')	
	Judicial[10] = new slctr("Acuerdos",'Acuerdos')
	Gobierno[11] = new slctr("Otros",'Otros')

var Fraccionamiento=new Array()
	Fraccionamiento[0] = new slctr('Categoria:')
	Fraccionamiento[1] = new slctr("Avisos de Afectación",'Avisos de Afectación')
	Fraccionamiento[2] = new slctr("Permisos de Construcción",'Permisos de Construcción')		
	Fraccionamiento[3] = new slctr("Notificaciones",'Notificaciones')		
	Fraccionamiento[4] = new slctr("Revocaciones",'Revocaciones')	
	Fraccionamiento[5] = new slctr("Aviso",'Aviso')	
	Fraccionamiento[6] = new slctr("Administrativo",'Administrativo')		
	Fraccionamiento[7] = new slctr("Vacancias",'Vacancias')	

var Edictos=new Array()
	Edictos[0] = new slctr('Categoria:')
	Edictos[1] = new slctr("Civil",'Civil')
	Edictos[2] = new slctr("Sucesorio",'Sucesorio')	
	Edictos[3] = new slctr("Hipotecario",'Hipotecario')
	Edictos[4] = new slctr("Mercantil",'Mercantil')
	Edictos[5] = new slctr("Ad-Perpetuam",'Ad-Perpetuam')
	Edictos[6] = new slctr("Divorcio",'Divorcio')
	Edictos[7] = new slctr("Otro",'Otro')		



var Otros=new Array()
	Otros[0] = new slctr('Categoria:')
	Otros[1] = new slctr("Acuerdos",'Acuerdos')
	Otros[2] = new slctr("Reglamentos",'Reglamentos')		
	Otros[3] = new slctr("Convocatorias",'Convocatorias')		
	Otros[4] = new slctr("Nombramientos",'Nombramientos')		
	Otros[5] = new slctr("Expropiaciones",'Expropiaciones')		
	Otros[6] = new slctr("Aviso Notarial",'Aviso Notarial')		
	
	

